version: '2'

services:
  elastic:
    restart: always
    image: code.ngcli.com:4567/hr/es-with-plugins
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms10g -Xmx10g"
    ports:
      - 9292:9200
      - 9393:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elastic:9200"
    ports:
      - "5601:5601"

volumes:
  esdata:
    driver: local
