version: "3"

services:
  db:
    image: bitnami/mariadb:latest
    restart: always
    container_name: "mariadb"
    environment:
      MARIADB_DATABASE: connect_two
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: shhh_very_secret
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
