version: "3"

services:
  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=R_woyoadmin
    volumes:
      - redis:/bitnami/redis
    command: /run.sh --maxmemory 2000mb
volumes:
  redis:
    driver: local
