version: '2'

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    container_name: "etcd_3_3"
    restart: always
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "https://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "https://0.0.0.0:2379"
      ETCDCTL_API: "3"
      ETCD_CLIENT_CERT_AUTH: "true"
      ETCD_TRUSTED_CA_FILE: "/default.etcd/ca-cert.pem"
      ETCD_CERT_FILE: "/default.etcd/server-cert.pem"
      ETCD_KEY_FILE: "/default.etcd/server-key.pem"
    volumes: 
      - ./default.etcd:/default.etcd
    ports:
    - 2379:2379
    - 2380:2380
    - 4001:4001
  etcd-manage:
    build: .
    container_name: "etcd-manage"
    restart: always
    volumes:
      - ./conf:/app/conf
    ports:
      - "9090:9090"

